name: Trivy SBOM Scan (C++ with Conan)

on:
  workflow_dispatch:
    inputs:
      src_repository:
        description: 'Source Repository (e.g., user/repo)'
        required: true
      src_branch:
        description: 'Branch of source repository'
        required: false
        default: 'main'

jobs:
  sbom:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read

    steps:
      # --- Setup Environment ---
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Checkout source repository
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.src_repository }}
          ref: ${{ inputs.src_branch }}
          path: project-src

      # --- Install and configure Conan ---
      - name: Install Conan
        run: |
          python -m pip install --upgrade pip
          pip install conan
          cd project-src
          conan profile detect --force
          conan install . --build=missing
          conan lock create conanfile.py --lockfile-out=conan.lock

      # --- Setup Trivy ---
      - name: Setup Trivy
        uses: aquasecurity/setup-trivy@v0.2.3

      # --- Generate SBOM for C++ + Conan ---
      - name: Generate SBOM (C++ + Conan)
        run: |
          mkdir -p sbom-output
          trivy fs ./project-src \
            --scanners vuln,license,secret \
            --list-all-pkgs \
            --include-non-failures \
            --format cyclonedx \
            -o sbom-output/sbom-cpp-conan.json

      # --- Upload SBOM artifact ---
      - name: Sanitize artifact name
        id: sanitize
        run: |
          SAFE_NAME=$(echo "${{ inputs.src_repository }}" | tr '/' '_')
          echo "name=$SAFE_NAME" >> $GITHUB_OUTPUT

      - name: Upload SBOM
        uses: actions/upload-artifact@v4
        with:
          name: sbom-${{ steps.sanitize.outputs.name }}
          path: sbom-output/sbom-cpp-conan.json
          if-no-files-found: warn
